# Generated by Django 4.2.4 on 2023-11-02 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_content'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='User',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='content',
            name='post',
            field=models.CharField(max_length=150),
        ),
    ]
