# Generated by Django 4.2.4 on 2023-12-03 05:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_follow'),
    ]

    operations = [
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='content_liking', to='network.content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_that_is_liking', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
