# Generated by Django 4.2.4 on 2023-12-18 06:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_content_likes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='likes',
        ),
    ]
